"""
src/utils/verify_family_name_blocking.py

Empirically measures whether the family_name_main "longest variant wins" collapse is
structurally blocking real ARC<->OAX matches from ever being scored by Splink -- the bug
documented in CLAUDE.md's "Next Priority" TODO (Erfani/Clarke cases) and confirmed a third
time via DP0345157_HansMuhlhaus (2026-08-25): ARC side has family_names=['muhlhaus'] (plain
ASCII, no diacritic to expand from); every one of his 4 OpenAlex fragments has
family_names containing BOTH 'muhlhaus' and 'muehlhaus', but family_name_main = max(...,
key=len) always picks 'muehlhaus' (9 chars beats 8) -- so the two sides' collapsed scalars
never match, even though a shared token genuinely exists in both sets.

This is a MEASUREMENT tool, not a claim. Run it before and after any fix to
family_name_main computation or Splink blocking rules -- the numbers here are the only
honest evidence that a fix actually changed anything, per the explicit 2026-08-25 direction:
"Write yourself a code to make sure that you have actually done what you say you have done."

Two checks:
1. Static audit -- every known call site that collapses a family-name SET to one scalar via
   longest-string-wins (max_by_len() or the equivalent inline max(..., key=len)), and
   whether it feeds a live Splink blocking rule (high stakes: silently makes a pair
   unreachable) or something else.
2. Empirical check -- for every ARC person with a ground-truth confirmed OAX match (resolved
   via 'orcid' in arc_oax_resolved.parquet -- the one bucket where the match is independently
   verified via an exact ORCID match, not just Splink's own scoring), does the ARC-side
   family_name_main STRING-EQUAL the OAX-side family_name_main? A mismatch here is proof
   that pair would never even be generated by block_on("family_name_main", "first_initial")
   -- it can only have been resolved via the ORCID force-add path, meaning if that person had
   no ORCID recorded, they would be structurally invisible to Splink regardless of how much
   real OpenAlex content they have.

CLI: .venv/bin/python -m src.utils.verify_family_name_blocking
"""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from config.settings import PROCESSED_DATA

REPO_ROOT = Path(__file__).resolve().parents[2]

# Registry of every known family-name-collapse call site, kept in sync with the codebase by
# hand -- audit_call_sites() below cross-checks this list's line numbers still point at a
# max_by_len()/max(..., key=len) call, so a silent drift (line moved, call site edited away)
# is caught as a FAILED check rather than silently trusting a stale registry.
CALL_SITES = [
    {
        "file": "src/00c_prepare_oax.py", "line": 228,
        "role": "OAX family_name_main (feeds 03_link_arc_oax.py blocking + scoring)",
        "feeds_blocking": True, "fix_status": "unfixed -- family_name_main itself is still a "
            "longest-wins scalar, kept as the EXACT-MATCH comparison level (the strongest signal "
            "when both sides DO agree). It is no longer the sole blocking signal: 03_link_arc_oax.py "
            "now ALSO blocks on list_has_any() over the full family_names set (2026-08-25), and "
            "scores a set-overlap-but-not-exact match via a dedicated comparison level instead of "
            "falling to ElseLevel.",
    },
    {
        "file": "src/03_link_arc_oax.py", "line": 67,
        "role": "ARC family_name_main (feeds 03_link_arc_oax.py blocking + scoring)",
        "feeds_blocking": True, "fix_status": "unfixed scalar (same as above); blocking now ALSO "
            "uses the full family_names set via list_has_any() (2026-08-25) -- see "
            "blocking_rules_to_generate_predictions and the new family_name_main comparison's "
            "'Set overlap' level. Blocks on family_names (display + alternatives combined), not "
            "just the display-derived half -- alternatives-contamination risk (Clarke/Erfani) is "
            "real for max_by_len()'s scalar collapse, but not for set-overlap blocking, where a "
            "spurious pair still has to survive full comparison scoring.",
    },
    {
        "file": "src/utils/awards_cif.py", "line": 595,
        "role": "AwardCIFItem.family_name_main (ARC item-level; feeds cluster_items() dedupe_only "
            "blocking)",
        "feeds_blocking": True, "fix_status": "not applicable -- an AwardCIFItem's own "
            "family_names list always has 0 or 1 entries (_name_forms() never produces multiple "
            "spelling variants for one ARC record -- a genuinely bidirectional bare<->digraph "
            "expansion on the ARC side was attempted 2026-08-25 and reverted after testing showed "
            "it corrupts unrelated names, e.g. 'Fuentes'->'funtes'; see names.py's own comment), "
            "so max(key=len) has nothing to collapse ambiguously at the item level. Verified via "
            "audit_item_family_names_are_singletons().",
    },
    {
        "file": "src/utils/awards_cif.py", "line": 1532,
        "role": "merge_same_grant_coinvestigators() same-grant auto-merge key (ARC-internal, "
            "cluster-level family_names union)",
        "feeds_blocking": False, "fix_status": "fixed 2026-08-25 -- now groups by ANY shared "
            "family_names token, not one longest-wins scalar.",
    },
    {
        "file": "src/utils/awards_cif.py", "line": 2077,
        "role": "compute_gap_candidates() under-merge grouping key (ARC-internal, "
            "cluster-level family_names union)",
        "feeds_blocking": False, "fix_status": "fixed 2026-08-25 -- now groups by ANY shared "
            "family_names token (deduplicated to unique pairs before compatibility checks), not "
            "one longest-wins scalar.",
    },
]

# Accepted limitation (2026-08-25), not pending work: if OpenAlex's OWN curated display_name
# uses an ASCII-only digraph spelling with NO literal diacritic character anywhere (e.g. a
# hypothetical author record reading "Muehlhaus" verbatim, never "Mühlhaus"), family_names
# would only ever contain {'muehlhaus'} on the OAX side -- ARC's bare 'muhlhaus' still wouldn't
# overlap. This is the direct, necessary cost of the corpus-grounded design already chosen over
# a blind substring fold (tried and rejected -- corrupts unrelated names, e.g. "Fuentes"
# -> "funtes"): a pairing is only ever trusted when independently confirmed elsewhere in the OAX
# corpus, so a name with no confirming sibling anywhere in 119M authors stays unmatched. Fixing
# it would mean reintroducing exactly the failure mode the corpus-grounded approach exists to
# avoid, or taking on an external linguistic reference-data dependency in 01_prepare_arc.py
# (deliberately kept OAX-independent) -- neither is a real improvement, so this stays accepted,
# not queued for a decision.


def audit_call_sites(verbose: bool = True) -> list[dict]:
    """Cross-check CALL_SITES against the actual source files -- catches registry drift (a line
    moved or a call site was edited away without updating this file)."""
    results = []
    for site in CALL_SITES:
        path = REPO_ROOT / site["file"]
        line_no = site["line"]
        ok = False
        actual_line = None
        if path.exists():
            lines = path.read_text().splitlines()
            if 0 < line_no <= len(lines):
                actual_line = lines[line_no - 1]
                ok = ("max_by_len(" in actual_line) or ("max(" in actual_line and "key=len" in actual_line)
        results.append({**site, "line_still_matches": ok, "actual_line": actual_line})
        if verbose:
            mark = "OK " if ok else "!! "
            print(f"{mark}{site['file']}:{line_no}  [{'BLOCKING' if site['feeds_blocking'] else 'other'}]")
            print(f"     role: {site['role']}")
            print(f"     status: {site['fix_status']}")
            if not ok:
                print(f"     WARNING: registry line no longer matches source -- re-audit needed. Actual: {actual_line!r}")
    return results


def audit_item_family_names_are_singletons() -> dict:
    """Verify the claim behind the 'not applicable' status on awards_cif.py:595 -- that every
    AwardCIFItem's own family_names list has at most 1 entry, so max(key=len) can't collapse
    away a genuine alternative there. Checked against the real persisted population, not
    assumed from reading the code."""
    from src.utils.awards_cif import load_award_cif_items
    items = load_award_cif_items()
    lens = [len(it.family_names) for it in items]
    multi = [it for it, n in zip(items, lens) if n > 1]
    return {
        "n_items": len(items),
        "max_family_names_len": max(lens) if lens else 0,
        "n_items_with_multiple": len(multi),
        "sample_multi": [(it.unique_id, it.family_names) for it in multi[:5]],
    }


def empirical_mismatch_check(verbose: bool = True) -> dict:
    """For every ARC person resolved via a ground-truth ORCID match, check whether ARC-side and
    OAX-side family_name_main actually agree. A mismatch is direct proof that pair would never
    have been generated by the scalar-equality blocking rule alone -- only the separate ORCID
    force-add path rescued it. Returns counts and the mismatch list (for anyone without an
    ORCID, this same failure mode would leave them with zero candidates, structurally, not just
    a low-confidence one)."""
    resolved = pd.read_parquet(PROCESSED_DATA / "arc_oax_resolved.parquet")
    persons = pd.read_parquet(PROCESSED_DATA / "awards_cif_arc_only.parquet")
    oax = pd.read_parquet(PROCESSED_DATA / "openalex_authors_prep.parquet")

    orcid_resolved = resolved[resolved["resolved_by"] == "orcid"][["arc_id", "oax_id"]]

    def _max_by_len(lst):
        if lst is None or len(lst) == 0:
            return None
        return max(lst, key=len)

    arc_fnm = persons.set_index("cluster_id")["family_names"].apply(_max_by_len)
    oax_fnm = oax.set_index("unique_id")["family_names"].apply(_max_by_len)

    rows = []
    for _, r in orcid_resolved.iterrows():
        a_fnm = arc_fnm.get(r["arc_id"])
        o_fnm = oax_fnm.get(r["oax_id"])
        if a_fnm is None or o_fnm is None:
            continue
        rows.append({
            "arc_id": r["arc_id"], "oax_id": r["oax_id"],
            "arc_family_name_main": a_fnm, "oax_family_name_main": o_fnm,
            "would_block": a_fnm == o_fnm,
        })
    df = pd.DataFrame(rows)
    n_total = len(df)
    n_mismatch = int((~df["would_block"]).sum()) if n_total else 0

    result = {
        "n_orcid_confirmed_pairs_checked": n_total,
        "n_would_not_block_on_family_name_main": n_mismatch,
        "mismatch_rate": round(n_mismatch / n_total, 4) if n_total else None,
        "mismatches": df[~df["would_block"]].to_dict("records") if n_total else [],
    }
    if verbose:
        print(f"\n  Checked {n_total} ORCID-confirmed ARC<->OAX pairs.")
        print(f"  {n_mismatch} ({result['mismatch_rate']:.2%}) would NOT have blocked on "
              f"family_name_main alone -- these were only reachable via the ORCID force-add "
              f"path. Anyone with the same family_name_main mismatch but NO recorded ORCID is "
              f"structurally invisible to blocking, regardless of real OpenAlex content.")
        if n_mismatch:
            print("  Sample mismatches:")
            for m in result["mismatches"][:10]:
                print(f"    {m['arc_id']}: arc={m['arc_family_name_main']!r} vs "
                      f"oax={m['oax_family_name_main']!r}")
    return result


def check_specific_case(cluster_id: str, verbose: bool = True) -> dict:
    """Named regression check -- does this specific ARC person now get >=1 high-confidence OAX
    candidate? Re-run this after any blocking-rule fix + a real 03_link_arc_oax.py rerun to
    prove a fix actually changed the pipeline's output, not just the source code."""
    links_path = PROCESSED_DATA / "arc_oax_links.parquet"
    links = pd.read_parquet(links_path)
    rows = links[links["arc_id"] == cluster_id]
    hc = rows[rows["high_confidence"] == True]
    result = {
        "cluster_id": cluster_id,
        "n_candidates_any_confidence": len(rows),
        "n_high_confidence": len(hc),
        "max_probability": float(rows["match_probability"].max()) if len(rows) else None,
        "links_file_mtime": pd.Timestamp(links_path.stat().st_mtime, unit="s"),
    }
    if verbose:
        print(f"\n  {cluster_id}: {result['n_candidates_any_confidence']} candidate(s), "
              f"{result['n_high_confidence']} high-confidence, "
              f"max probability {result['max_probability']}")
        print(f"  (arc_oax_links.parquet last modified: {result['links_file_mtime']})")
    return result


def main():
    print("=== 1. Static call-site audit ===")
    audit_call_sites()

    print("\n=== 2. AwardCIFItem.family_names singleton check ===")
    r = audit_item_family_names_are_singletons()
    print(f"  {r['n_items']} items, max family_names length = {r['max_family_names_len']}, "
          f"{r['n_items_with_multiple']} with >1 entry")

    print("\n=== 3. Empirical mismatch check (ORCID-confirmed ground truth) ===")
    empirical_mismatch_check()

    print("\n=== 4. Named regression case: DP0345157_HansMuhlhaus ===")
    check_specific_case("DP0345157_HansMuhlhaus")


if __name__ == "__main__":
    main()
